### ISSUE TITLE
target install missing in makefile

### ISSUE THREAD

**Issue by leenaars** [cr-marcstevens/sha1collisiondetection#1]
Hi Marc,

awesome work. One small comment: the target install is missing in the Makefile.
Also, could you add a version number to the release, so one can refer to it?

**Comment by muellermartin** [comment]
Hi, I've included this target (including the `uninstall` target) in PR #4 to support macOS (see commit c220376). If you wish I'll cherry pick this feature and include it in a seperate PR (this will likely result in a merge conflict in case the macOS support PR ever gets merged - but this should be rather trivial to merge I think).

**Comment by muellermartin** [comment]
Fixed in PR #15.
