### ISSUE TITLE
Tag for release

### ISSUE THREAD

**Issue by johnhawkinson** [cr-marcstevens/sha1collisiondetection#11]
The homebrew folks (MacOS package manager) would like a git tag for a release (be it stable or development). Can you please create a tag?

Thanks.

cf. https://github.com/Homebrew/homebrew-core/pull/10431/files/f74798d7662c777d29b9cabce1ebb0cbf1bb93b5

**Comment by cr-marcstevens** [comment]
Sure, will do so asap after a bit more cleaning up and checking.

**Comment by cr-marcstevens** [comment]
Done!
