### ISSUE TITLE
Example in Readme needs an update

### ISSUE THREAD

**Issue by oparoz** [cr-marcstevens/sha1collisiondetection#18]
The example commands don't work anymore since the binary has been renamed and there seems to be a single binary now (2nd one is a symlink)

**Comment by muellermartin** [comment]
Does it work if you use the renamed commands (`sha1dcsum` and `sha1dcsum_partialcoll`)? The 2nd binary was only a copy of the first one which had different functionality based on the name, as far as I know, so basically it should work if you use the new names.

**Comment by cr-marcstevens** [comment]
Thanks for spotting this, but should be fixed in master now.
