### ISSUE TITLE
Does not work with Checkinstall

### ISSUE THREAD

**Issue by gabrielbouzard** [cr-marcstevens/sha1collisiondetection#21]
Checkinstall does not give any installation erros, but runnig the samples results in: 

> error while loading shared libraries: libsha1detectcoll.so.0: cannot open shared object file: No such file or directory

**Comment by cr-marcstevens** [comment]
Thanks for posting this issue.
Can you provide more information?
What are the exact steps you took and can you give a log of all output?
Where were the files installed and what was the value of the PREFIX environment variable?
