### ISSUE TITLE
Workaround for git using SHA2-512 exists

### ISSUE THREAD

**Issue by ypid** [cr-marcstevens/sha1collisiondetection#3]
I just wanted to mention that there exists a "workaround" for git called [git-evtag](https://github.com/cgwalters/git-evtag) which only relies on the cryptographically strong(er) hash function SHA2-512 and includes that into a (OpenPGP signed) git tag. Maybe you will consider using git-evtag to provide a strong checksum over your tags/releases :wink:

Which brings us to OpenPGP. As mentioned by @nbraud in [this comment](https://github.com/QubesOS/qubes-issues/issues/2240#issuecomment-239650738):

> Note that OpenPGP signatures are also vulnerable to SHA1 second-preimage attacks (the adversary can forge keys with specific keyids at that point).

([RFC4880, 12.2. Key IDs and Fingerprints](https://tools.ietf.org/html/rfc4880#page-71))

Does anyone know if someone is working on solving these issues for git and OpenPGP?

**Comment by muellermartin** [comment]
There is currently a discussion on the Git mailing list (was [featured on Hacker News](https://news.ycombinator.com/item?id=13719368)): http://marc.info/?l=git&m=148787047422954

**Comment by cr-marcstevens** [comment]
Before using git-evtag we need to first establish a developer public key, I'll confer with Dan Shumow.

It seems Jeff King is making an attempt at using sha1collisiondetection in git, which would also resolve this issue:
http://marc.info/?l=git&m=148789111730142&w=2
