### ISSUE TITLE
[RESEARCH] How to make it widespread

### ISSUE THREAD

**Issue by sergeevabc** [cr-marcstevens/sha1collisiondetection#49]
Dear Marc Stevens and Dan Shumow,
There are a variety of tools to calculate SHA1 that could benefit from including your library.
But what’s the proper argumentation to move its authors to do that?
For example, I [asked][1] RHash’s author to “reinforce SHA1 against collisions” which led to confusion.

[1]: https://github.com/rhash/RHash/issues/87

**Comment by shumow** [comment]
I see @cr-marcstevens weighed in on the thread that you used.  His argument is pretty good.  I would just try to show and argue what potential security ramifications a SHA-1 collision could cause.

**Comment by shumow** [comment]
Also, I'm going to close this, as it is not an "issue" with our library, per se.
