### ISSUE TITLE
document shambles detection status

### ISSUE THREAD

**Issue by graingert** [cr-marcstevens/sha1collisiondetection#53]
https://sha-mbles.github.io/

**Comment by graingert** [comment]
@cr-marcstevens

**Comment by cr-marcstevens** [comment]
I'm aware of the result, but I don't know what the issue is that you are reporting here.

**Comment by graingert** [comment]
@cr-marcstevens I'm assuming that the result demonstrated by shambles is already detected my SHA1DC?
