### ISSUE TITLE
@cr-marcstevens perhaps it's worth adding shambles messageA and messageB as test cases?

### ISSUE THREAD

**Issue by muhamadhermansyah** [cr-marcstevens/sha1collisiondetection#55]
@cr-marcstevens perhaps it's worth adding shambles messageA and messageB as test cases?

_Originally posted by @graingert in https://github.com/cr-marcstevens/sha1collisiondetection/pull/54#issuecomment-572256153_

**Comment by muhamadhermansyah** [comment]
Ok

**Comment by cr-marcstevens** [comment]
https://github.com/cr-marcstevens/sha1collisiondetection/blob/master/test/sha-mbles-1.bin

**Comment by cr-marcstevens** [comment]
Thanks for the suggestion, but as you can see these have already been added.
